language: php

git:
  depth: 1000

php:
  - 7.2

branches:
  only:
    master

addons:
  sonarcloud:
    organization: "fanchoop-github"
    token:
      secure: ••••••••••••••••
      

jdk:
  - oraclejdk8

script:
  - sonar-scanner
