language: php

git:
  depth: 1000

php:
  - 7.2

branches:
  only:
    master

install:
  - php composer.phar install --dev --no-interaction

addons:
  sonarcloud:
    organization: "fanchoop-github"
    token:
      secure: "db29f878472591c66d69eae3f1fc82d1f0124568"
      

jdk:
  - oraclejdk8

script:
  - ./vendor/bin/phpunit
  - sonar-scanner
