language: php

git:
  depth: 1000

php:
  - 7.2

branches:
  only:
    master

addons:
  sonarcloud:
    organization: "fanchoop-github"
    token:
      secure: "db29f878472591c66d69eae3f1fc82d1f0124568"
      

jdk:
  - oraclejdk8

script:
  - sonar-scanner
