language: php

git:
  depth: 1000

php:
  - 7.2

branches:
  only:
    master

addons:
  sonarcloud:
    organization: "fanchoop-github"
    token:
      secure: "92109656274faebb5a4bf2873cee93f585ab6c67"
      

jdk:
  - oraclejdk8

script:
  - sonar-scanner
